# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bvKtzLtwcnhS8YtFTKQqAGlLyfWc3MmO
"""

Student Enrollment Form that will store data in STUDENT-TABLE relation of SCHOOL-DB database.

Input Fields: {Roll-No, Full-Name, Class, Birth-Date, Address, Enrollment-Date}

Primary key: Roll No.

student enrollment form that stores data in the STUDENT-TABLE relation of the SCHOOL-DB database using PHP and MySQL.

<!DOCTYPE html>
<html>
<head>
	<title>Student Enrollment Form</title>
</head>
<body>
	<h2>Student Enrollment Form</h2>
	<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">
		Roll No.: <input type="text" name="roll_no" required><br><br>
		Full Name: <input type="text" name="full_name" required><br><br>
		Class: <input type="text" name="class" required><br><br>
		Birth Date: <input type="date" name="birth_date" required><br><br>
		Address: <textarea name="address" rows="5" cols="30" required></textarea><br><br>
		Enrollment Date: <input type="date" name="enrollment_date" required><br><br>
		<input type="submit" name="save" value="Save">
		<input type="submit" name="update" value="Update" disabled>
		<input type="submit" name="reset" value="Reset" disabled>
	</form>

	<?php
		// establish database connection
		$servername = "localhost";
		$username = "username";
		$password = "password";
		$dbname = "SCHOOL-DB";

		$conn = new mysqli($servername, $username, $password, $dbname);

		// check database connection
		if ($conn->connect_error) {
			die("Connection failed: " . $conn->connect_error);
		}

		// check if save button is clicked
		if (isset($_POST['save'])) {
			// get input data
			$roll_no = $_POST['roll_no'];
			$full_name = $_POST['full_name'];
			$class = $_POST['class'];
			$birth_date = $_POST['birth_date'];
			$address = $_POST['address'];
			$enrollment_date = $_POST['enrollment_date'];

			// check if roll no. already exists in database
			$sql_check = "SELECT * FROM STUDENT-TABLE WHERE `Roll-No`='$roll_no'";
			$result_check = $conn->query($sql_check);

			if ($result_check->num_rows > 0) {
				echo "<script>alert('Roll No. already exists. Please try again.')</script>";
			} else {
				// insert data into database
				$sql_insert = "INSERT INTO STUDENT-TABLE (`Roll-No`, `Full-Name`, `Class`, `Birth-Date`, `Address`, `Enrollment-Date`) VALUES ('$roll_no', '$full_name', '$class', '$birth_date', '$address', '$enrollment_date')";
				$result_insert = $conn->query($sql_insert);

				if ($result_insert === TRUE) {
					echo "<script>alert('Data saved successfully.')</script>";
					echo "<script>window.location.reload()</script>";
				} else {
					echo "<script>alert('Error: " . $sql_insert . "<br>" . $conn->error . "')</script>";
				}
			}
		}

		// check if update button is clicked
		if (isset($_POST['update'])) {
			// get input data
			$roll_no = $_POST['roll_no'];
			$full_name = $_POST['full_name'];
			$class = $_POST['class'];
			$birth_date = $_

Product Inventory Form that will store data in PRODUCT-TABLE relation of STORE-DB database.

Input Fields: {Product-ID, Product-Name, Product-Description, Quantity, Unit-Price}

Primary key: Product-ID

<!DOCTYPE html>
<html>
<head>
	<title>Product Inventory Form</title>
	<script>
		window.onload = function() {
			document.getElementById("product-id").focus();
			document.getElementById("save-btn").disabled = true;
			document.getElementById("update-btn").disabled = true;
			document.getElementById("reset-btn").disabled = true;
		}
		
		function validateForm() {
			var productId = document.forms["inventoryForm"]["product-id"].value;
			var productName = document.forms["inventoryForm"]["product-name"].value;
			var productDesc = document.forms["inventoryForm"]["product-desc"].value;
			var quantity = document.forms["inventoryForm"]["quantity"].value;
			var unitPrice = document.forms["inventoryForm"]["unit-price"].value;
			if (productId == "" || productName == "" || productDesc == "" || quantity == "" || unitPrice == "") {
				alert("Please fill all fields!");
				return false;
			}
		}
		
		function checkProductId() {
			var productId = document.forms["inventoryForm"]["product-id"].value;
			var xhttp = new XMLHttpRequest();
			xhttp.onreadystatechange = function() {
				if (this.readyState == 4 && this.status == 200) {
					if (this.responseText == "exists") {
						// product ID already exists in database, enable update and reset buttons and populate form with existing data
						document.getElementById("update-btn").disabled = false;
						document.getElementById("reset-btn").disabled = false;
						document.getElementById("product-name").disabled = false;
						document.getElementById("product-desc").disabled = false;
						document.getElementById("quantity").disabled = false;
						document.getElementById("unit-price").disabled = false;
						document.getElementById("product-name").focus();
						var data = JSON.parse(this.responseText.substring(6));
						document.getElementById("product-name").value = data.product_name;
						document.getElementById("product-desc").value = data.product_desc;
						document.getElementById("quantity").value = data.quantity;
						document.getElementById("unit-price").value = data.unit_price;
					} else {
						// product ID does not exist in database, enable save and reset buttons and move cursor to next field
						document.getElementById("save-btn").disabled = false;
						document.getElementById("reset-btn").disabled = false;
						document.getElementById("product-name").disabled = false;
						document.getElementById("product-desc").disabled = false;
						document.getElementById("quantity").disabled = false;
						document.getElementById("unit-price").disabled = false;
						document.getElementById("product-name").focus();
					}
				}
			};
			xhttp.open("GET", "check_product_id.php?product_id=" + productId, true);
			xhttp.send();
		}
		
		function resetForm() {
			document.getElementById("inventoryForm").reset();
			document.getElementById("product-id").disabled = false;
			document.getElementById("product-name").disabled = true;
			document.getElementById("product-desc").disabled = true;
			document.getElementById("quantity").disabled = true;
			document.getElementById("unit-price").disabled = true;
			document.getElementById("save-btn").disabled = true;
			document.getElementById("update-btn").disabled = true;
			document.getElementById("reset-btn").disabled = true;
			document.getElementById("product-id").focus();
		}
	</script>
</head>
<body>
	<h2>Product Inventory Form</h2>
	<form name="inventoryForm" onsubmit="return validateForm()" method="post"